name: Build and Release Arch ISO

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs at midnight UTC on the 1st of every month
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Arch ISO in Docker
        run: |
          docker run --rm --privileged -v $PWD:/build -w /build archlinux:latest bash -c "
            pacman -Sy --noconfirm archiso &&
            mkdir -p work out &&
            mkarchiso -v -w work -o out .
          "

      - name: Rename and Move ISO
        run: |
          ISO_DATE=$(date -I)  # Get ISO 8601 date (YYYY-MM-DD)
          ISO_NAME="ArchUtils-${ISO_DATE}.iso"
          mv out/*.iso "out/$ISO_NAME"
          echo "ISO_NAME=$ISO_NAME" >> $GITHUB_ENV
          echo "ISO_DATE=$ISO_DATE" >> $GITHUB_ENV

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archiso
          path: out/*.iso

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download ISO Artifact
        uses: actions/download-artifact@v4
        with:
          name: archiso
          path: out

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "monthly-build-${{ env.ISO_DATE }}"  # Tag for tracking
          name: "Build ${{ env.ISO_DATE }}"  # Release name
          body: "Automated monthly build of ArchUtils for ${{ env.ISO_DATE }}"
          files: out/*.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
